### ISSUE TITLE
Issue with @import encountered and resolved

### ISSUE THREAD

**Issue by dzoba** [jonathanepollack/gulp-minify-css#56]
I'm leaving this here for others who may come into contact with this issue (as we did) after gulp-minify-css's recent update of clean-css.  After clean-css version 2.1.0, clean-css will fail if the url in an @import statement isn't reachable.

In our case, we use fonts from typography.com and the url isn't directly reachable (403), so suddenly our builds started failing.  We resolved this by including the font directly in the head tag of our site, rather than through our css file.

**Comment by rogierschouten** [comment]
Does this error manifest itself this way in Gulp?

```shell
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DestroyableTransform.emit (events.js:74:15)
    at DestroyableTransform.onerror (_stream_readable.js:537:12)
    at DestroyableTransform.emit (events.js:95:17)
    at onwriteError (b:\exlent\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (b:\exlent\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
    at WritableState.onwrite (b:\exlent\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
    at afterTransform (b:\exlent\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
    at TransformState.afterTransform (b:\exlent\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at b:\exlent\node_modules\gulp-minify-css\index.js:87:9
    at b:\exlent\node_modules\gulp-minify-css\index.js:35:7
    at whenSourceMapReady (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:89:16)
    at Object.whenDone (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:98:14)
    at processNext (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:105:13)
    at importFrom (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:79:10)
    at processNext (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:104:16)
    at inlineLocalResource (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:290:12)
    at inline (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:209:10)
    at importFrom (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:74:7)
    at ImportInliner.process (b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\imports\inliner.js:36:10)
    at b:\exlent\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:71:41
    at process._tickDomainCallback (node.js:486:13) Build step 'Execute shell' marked build as failure

```

**Comment by jonathanepollack** [comment]
So... is this resolved?

**Comment by rogierschouten** [comment]
To answer my own question: yes this was an @import error. 
I think it is a bug that gulp-minify-css does not emit the proper error to gulp.

**Comment by jonathanepollack** [comment]
So there was no resolution?

**Comment by jonathanepollack** [comment]
So I'm fairly sure we just went through the whole [Megillah](https://en.wikipedia.org/wiki/Megillah_(Talmud)) dealing with this on #61. I'm going to close this issue as this it seems like this error comes from `inliner` (a `clean-css` module), when it can't find the file you're trying to import.

If you're having this issue, please use the `gulp-minify-css` option `{processImport: false}`.
