### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by iongion** [jonathanepollack/gulp-minify-css#70]
My gulpfile task looks like this:

```
gulp.task('vendors.sources.css', function() {
  return gulp.src('vendors/css/**/**')
    .pipe(sourcemaps.init())
    .pipe(minifyCSS())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('build/css'))
})
```

I have no idea what this stacktrace means

```
gulp-minify-css\node_modules\clean-css\lib\text\escape-store.js:49
  var index = this.restoreMatcher.exec(placeholder)[1];
                                                   ^
TypeError: Cannot read property '1' of null
    at EscapeStore.restore (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\text\escape-store.js:49:52)
    at FreeTextProcessor.restore (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\text\free-text-processor.js:78:39)
    at Rebuilder.restore (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:163:32)
    at Rebuilder.store (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\selectors\source-map-stringifier.js:63:42)
    at Rebuilder.rebuildValue (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\selectors\source-map-stringifier.js:53:12)
    at Rebuilder.rebuildList (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\selectors\source-map-stringifier.js:95:12)
    at SourceMapStringifier.toString (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\selectors\source-map-stringifier.js:149:18)
    at SelectorsOptimizer.process (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\selectors\optimizer.js:17:22)
    at W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:170:31
    at run (W:\Workspace\Project\node_modules\gulp-minify-css\node_modules\clean-css\lib\clean.js:149:7)

```

**Comment by shinnn** [comment]
Please update your task like this and try again:

`vendors/css/**/**` -> `vendors/css/**/**.css`

**Comment by steveed** [comment]
I am having the same issue.

    gulp.task('styles', function() {
      return gulp.src(directories.css)
        .pipe(autoprefixer('last 2 versions', '> 1%', 'ie 8'))
        .pipe(concatCss("bundle.css"))
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(minifyCSS())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('public/css/'));
    });

Directories CSS is:

      css: [
         './node_modules/bootstrap/dist/css/bootstrap.css',
         './node_modules/angular-xeditable/dist/css/xeditable.css',
         './client/static/**/*.css'
      ],

I tried removing everything and just having `./client/static/**/*.css` but that did not help.

**Comment by wavded** [comment]
I also am having the same issue.

**Comment by iongion** [comment]
Back on this, shinnn recommendation fixed the issue, basically the css processor encounters invalid files in the stream. There is this nice tool https://www.npmjs.com/package/gulp-debug that you can use to see what streams minifyCSS receives, it might help you if you have a different issue.

I will close this as fixed, I guess it can be re-opened if you really find something else.

**Comment by steveed** [comment]
Hmm, shinnn's recommendation did not fix the error for me. I did some debugging on my css files and found that it occurs whenever the parser encounters the following syntax

    .oneSelector .twoSelector:not(.otherSelector) { }

**Comment by iongion** [comment]
digg deper and report it to the parser people if it is the case
